/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.aedu.anhanghera.poo.biblioteca.gui;

import br.aedu.anhanghera.poo.biblioteca.dominio.Livro;
import br.aedu.anhanghera.poo.biblioteca.gui.model.LivroTableModel;
import br.aedu.anhanghera.poo.biblioteca.gui.table.ButtonColumn;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author 98379720172
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        livrosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Cadastros");

        livrosMenuItem.setMnemonic('l');
        livrosMenuItem.setText("Livros");
        livrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(livrosMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void livrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosMenuItemActionPerformed
        FrameLivros fl = new FrameLivros();
        List<Livro> livros = new ArrayList<>();

        Livro l = new Livro();
        l.setId(1);
        l.setNome("teste");
        l.setIsbn("1212121");
        
          Livro l2 = new Livro();
        l2.setId(2);
        l2.setNome("teste 2");
        l2.setIsbn("1212121");

        livros.add(l);
        livros.add(l2);

        LivroTableModel tm = new LivroTableModel(livros);

        fl.setTblLivrosTableModel(tm);

        Action excluir = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                
                JOptionPane.showMessageDialog(JanelaPrincipal.this, "Excluir Registro "+fl.tblLivros.getSelectedRow());
                fl.tblLivros.clearSelection();
            }
        };
        
        ButtonColumn btn = new ButtonColumn(fl.tblLivros, excluir, 3);

        fl.tblLivros.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (fl.tblLivros.getSelectedRow() > -1) {

                    LivroTableModel tm = (LivroTableModel) fl.tblLivros.getModel();
                    Livro livro = tm.getValueAt(fl.tblLivros.getSelectedRow());

                    fl.txId.setText(String.valueOf(livro.getId()));
                    fl.txNome.setText(livro.getNome());
                    fl.txIsbn.setText(livro.getIsbn());
                }
            }
        });

        desktopPane.add(fl);
        fl.setVisible(true);
    }//GEN-LAST:event_livrosMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem livrosMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
